/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const InquiryStatus = IDL.Variant({
  'new' : IDL.Null,
  'closed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Inquiry = IDL.Record({
  'id' : IDL.Nat,
  'status' : InquiryStatus,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Response = IDL.Record({
  'message' : IDL.Text,
  'success' : IDL.Bool,
});

export const idlService = IDL.Service({
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getInquiriesByStatus' : IDL.Func(
      [InquiryStatus],
      [IDL.Vec(Inquiry)],
      ['query'],
    ),
  'getInquiryById' : IDL.Func([IDL.Nat], [Inquiry], ['query']),
  'submitInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Response], []),
  'updateInquiryStatus' : IDL.Func([IDL.Nat, InquiryStatus], [Response], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const InquiryStatus = IDL.Variant({
    'new' : IDL.Null,
    'closed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Inquiry = IDL.Record({
    'id' : IDL.Nat,
    'status' : InquiryStatus,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Response = IDL.Record({ 'message' : IDL.Text, 'success' : IDL.Bool });
  
  return IDL.Service({
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getInquiriesByStatus' : IDL.Func(
        [InquiryStatus],
        [IDL.Vec(Inquiry)],
        ['query'],
      ),
    'getInquiryById' : IDL.Func([IDL.Nat], [Inquiry], ['query']),
    'submitInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Response], []),
    'updateInquiryStatus' : IDL.Func([IDL.Nat, InquiryStatus], [Response], []),
  });
};

export const init = ({ IDL }) => { return []; };