/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem {
  'productId' : string,
  'addedAt' : bigint,
  'quantity' : bigint,
}
export interface ContactFormResponse {
  'message' : string,
  'success' : boolean,
  'submissionId' : [] | [string],
}
export interface ContactSubmission {
  'id' : string,
  'customerName' : string,
  'submittedAt' : bigint,
  'message' : [] | [string],
  'address' : string,
  'customerEmail' : string,
}
export interface ContactSubmissionListResponse {
  'submissions' : Array<ContactSubmission>,
  'success' : boolean,
}
export interface Order {
  'id' : string,
  'customerName' : string,
  'status' : OrderStatus,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'totalAmount' : bigint,
  'shippingAddress' : string,
  'items' : Array<CartItem>,
  'customerEmail' : string,
}
export interface OrderListResponse {
  'orders' : Array<Order>,
  'success' : boolean,
}
export interface OrderResponse {
  'orderId' : [] | [string],
  'message' : string,
  'success' : boolean,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'processing' : null };
export interface OrderStatusResponse {
  'order' : [] | [Order],
  'message' : string,
  'success' : boolean,
}
export interface Product {
  'id' : string,
  'inStock' : boolean,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'benefits' : Array<string>,
  'price' : bigint,
  'variant' : string,
}
export interface ProductDeleteResponse {
  'deletedProductId' : [] | [string],
  'message' : string,
  'success' : boolean,
}
export interface ProductListResponse {
  'success' : boolean,
  'products' : Array<Product>,
}
export interface ProductResponse {
  'success' : boolean,
  'product' : [] | [Product],
}
export interface ProductUpdateResponse {
  'message' : string,
  'success' : boolean,
  'product' : [] | [Product],
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addProduct' : ActorMethod<
    [string, string, string, bigint, string, Array<string>, string, boolean],
    ProductResponse
  >,
  'deleteProduct' : ActorMethod<[string], ProductDeleteResponse>,
  'getAllContactSubmissions' : ActorMethod<[], ContactSubmissionListResponse>,
  'getOrderById' : ActorMethod<[string], OrderStatusResponse>,
  'getOrdersByStatus' : ActorMethod<[OrderStatus], OrderListResponse>,
  'getProductById' : ActorMethod<[string], ProductResponse>,
  'getProducts' : ActorMethod<[], ProductListResponse>,
  'submitContactForm' : ActorMethod<
    [string, string, string, [] | [string]],
    ContactFormResponse
  >,
  'submitOrder' : ActorMethod<
    [Array<CartItem>, string, string, string],
    OrderResponse
  >,
  'updateOrderStatus' : ActorMethod<[string, OrderStatus], OrderStatusResponse>,
  'updateProduct' : ActorMethod<
    [string, string, string, bigint, string, Array<string>, string, boolean],
    ProductUpdateResponse
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];