/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'inStock' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'benefits' : IDL.Vec(IDL.Text),
  'price' : IDL.Nat,
  'variant' : IDL.Text,
});
export const ProductResponse = IDL.Record({
  'success' : IDL.Bool,
  'product' : IDL.Opt(Product),
});
export const ProductDeleteResponse = IDL.Record({
  'deletedProductId' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
  'success' : IDL.Bool,
});
export const ContactSubmission = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'submittedAt' : IDL.Int,
  'message' : IDL.Opt(IDL.Text),
  'address' : IDL.Text,
  'customerEmail' : IDL.Text,
});
export const ContactSubmissionListResponse = IDL.Record({
  'submissions' : IDL.Vec(ContactSubmission),
  'success' : IDL.Bool,
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'processing' : IDL.Null,
});
export const CartItem = IDL.Record({
  'productId' : IDL.Text,
  'addedAt' : IDL.Int,
  'quantity' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'totalAmount' : IDL.Nat,
  'shippingAddress' : IDL.Text,
  'items' : IDL.Vec(CartItem),
  'customerEmail' : IDL.Text,
});
export const OrderStatusResponse = IDL.Record({
  'order' : IDL.Opt(Order),
  'message' : IDL.Text,
  'success' : IDL.Bool,
});
export const OrderListResponse = IDL.Record({
  'orders' : IDL.Vec(Order),
  'success' : IDL.Bool,
});
export const ProductListResponse = IDL.Record({
  'success' : IDL.Bool,
  'products' : IDL.Vec(Product),
});
export const ContactFormResponse = IDL.Record({
  'message' : IDL.Text,
  'success' : IDL.Bool,
  'submissionId' : IDL.Opt(IDL.Text),
});
export const OrderResponse = IDL.Record({
  'orderId' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
  'success' : IDL.Bool,
});
export const ProductUpdateResponse = IDL.Record({
  'message' : IDL.Text,
  'success' : IDL.Bool,
  'product' : IDL.Opt(Product),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Bool,
      ],
      [ProductResponse],
      [],
    ),
  'deleteProduct' : IDL.Func([IDL.Text], [ProductDeleteResponse], []),
  'getAllContactSubmissions' : IDL.Func(
      [],
      [ContactSubmissionListResponse],
      ['query'],
    ),
  'getOrderById' : IDL.Func([IDL.Text], [OrderStatusResponse], ['query']),
  'getOrdersByStatus' : IDL.Func([OrderStatus], [OrderListResponse], ['query']),
  'getProductById' : IDL.Func([IDL.Text], [ProductResponse], ['query']),
  'getProducts' : IDL.Func([], [ProductListResponse], ['query']),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [ContactFormResponse],
      [],
    ),
  'submitOrder' : IDL.Func(
      [IDL.Vec(CartItem), IDL.Text, IDL.Text, IDL.Text],
      [OrderResponse],
      [],
    ),
  'updateOrderStatus' : IDL.Func(
      [IDL.Text, OrderStatus],
      [OrderStatusResponse],
      [],
    ),
  'updateProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Bool,
      ],
      [ProductUpdateResponse],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'inStock' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'benefits' : IDL.Vec(IDL.Text),
    'price' : IDL.Nat,
    'variant' : IDL.Text,
  });
  const ProductResponse = IDL.Record({
    'success' : IDL.Bool,
    'product' : IDL.Opt(Product),
  });
  const ProductDeleteResponse = IDL.Record({
    'deletedProductId' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
    'success' : IDL.Bool,
  });
  const ContactSubmission = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'submittedAt' : IDL.Int,
    'message' : IDL.Opt(IDL.Text),
    'address' : IDL.Text,
    'customerEmail' : IDL.Text,
  });
  const ContactSubmissionListResponse = IDL.Record({
    'submissions' : IDL.Vec(ContactSubmission),
    'success' : IDL.Bool,
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'processing' : IDL.Null,
  });
  const CartItem = IDL.Record({
    'productId' : IDL.Text,
    'addedAt' : IDL.Int,
    'quantity' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'totalAmount' : IDL.Nat,
    'shippingAddress' : IDL.Text,
    'items' : IDL.Vec(CartItem),
    'customerEmail' : IDL.Text,
  });
  const OrderStatusResponse = IDL.Record({
    'order' : IDL.Opt(Order),
    'message' : IDL.Text,
    'success' : IDL.Bool,
  });
  const OrderListResponse = IDL.Record({
    'orders' : IDL.Vec(Order),
    'success' : IDL.Bool,
  });
  const ProductListResponse = IDL.Record({
    'success' : IDL.Bool,
    'products' : IDL.Vec(Product),
  });
  const ContactFormResponse = IDL.Record({
    'message' : IDL.Text,
    'success' : IDL.Bool,
    'submissionId' : IDL.Opt(IDL.Text),
  });
  const OrderResponse = IDL.Record({
    'orderId' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
    'success' : IDL.Bool,
  });
  const ProductUpdateResponse = IDL.Record({
    'message' : IDL.Text,
    'success' : IDL.Bool,
    'product' : IDL.Opt(Product),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Bool,
        ],
        [ProductResponse],
        [],
      ),
    'deleteProduct' : IDL.Func([IDL.Text], [ProductDeleteResponse], []),
    'getAllContactSubmissions' : IDL.Func(
        [],
        [ContactSubmissionListResponse],
        ['query'],
      ),
    'getOrderById' : IDL.Func([IDL.Text], [OrderStatusResponse], ['query']),
    'getOrdersByStatus' : IDL.Func(
        [OrderStatus],
        [OrderListResponse],
        ['query'],
      ),
    'getProductById' : IDL.Func([IDL.Text], [ProductResponse], ['query']),
    'getProducts' : IDL.Func([], [ProductListResponse], ['query']),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [ContactFormResponse],
        [],
      ),
    'submitOrder' : IDL.Func(
        [IDL.Vec(CartItem), IDL.Text, IDL.Text, IDL.Text],
        [OrderResponse],
        [],
      ),
    'updateOrderStatus' : IDL.Func(
        [IDL.Text, OrderStatus],
        [OrderStatusResponse],
        [],
      ),
    'updateProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Bool,
        ],
        [ProductUpdateResponse],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };